import type { Context } from "telegraf";

import { consumeLinkCode } from "@nemesis/db";
import { linkedWalletKeyboard, shortWallet, unlinkedWalletKeyboard } from "../lib/ui.js";

/**
 * Consumes a one-time code generated by POST /api/link/generate on the
 * web dashboard. Usage: /link <CODE>
 *
 * On success, stores the Telegram chat ID against the wallet address in
 * the database - from that point on, all proposals for agents belonging
 * to that wallet are delivered to this chat. This is the production wallet<->Telegram linking flow.
 */
export async function linkCommand(ctx: Context): Promise<void> {
  const text = ctx.message && "text" in ctx.message ? ctx.message.text : "";
  const [, code] = text.trim().split(/\s+/);
  const chatId = String(ctx.chat?.id ?? "");

  if (!code) {
    await ctx.reply(
      [
        "Generate a linking code from the NEMESIS dashboard, then send:",
        "<code>/link YOUR-CODE</code>",
      ].join("\n"),
      { parse_mode: "HTML", ...unlinkedWalletKeyboard() },
    );
    return;
  }

  const result = await consumeLinkCode(code.toUpperCase(), chatId);

  if (!result.ok) {
    const messages: Record<string, string> = {
      "not-found": "Code not found. Make sure you copied it correctly from the dashboard.",
      "expired": "Code has expired (codes are valid for 10 minutes). Generate a new one from the dashboard.",
      "already-used": "Code has already been used. Generate a new one from the dashboard.",
    };
    await ctx.reply(messages[result.reason] ?? "Something went wrong. Please try again.", unlinkedWalletKeyboard());
    return;
  }

  const short = shortWallet(result.walletAddress);
  await ctx.reply(
    [
      "<b>Linked.</b>",
      `Wallet <code>${short}</code> is now connected to this chat.`,
      "Agent proposals will be delivered here from now on.",
      "Use /agents to list agents or /status to check runtime state.",
    ].join("\n"),
    { parse_mode: "HTML", ...linkedWalletKeyboard() },
  );
}

/**
 * /unlink - removes the wallet<->chat mapping so proposals stop arriving.
 */
export async function unlinkCommand(ctx: Context): Promise<void> {
  const chatId = String(ctx.chat?.id ?? "");
  const { getWalletForTelegramChatId, pool } = await import("@nemesis/db");
  const wallet = await getWalletForTelegramChatId(chatId);

  if (!wallet) {
    await ctx.reply("This chat is not linked to any wallet.", unlinkedWalletKeyboard());
    return;
  }

  await pool.query("UPDATE users SET telegram_chat_id = NULL WHERE wallet_address = $1", [wallet]);

  const short = shortWallet(wallet);
  await ctx.reply(`Wallet <code>${short}</code> has been unlinked. Proposals will no longer be sent here.`, {
    parse_mode: "HTML",
    ...unlinkedWalletKeyboard(),
  });
}