import type { Context } from "telegraf";

import { consumeLinkCode } from "@nemesis/db";
import { linkedWalletKeyboard, shortWallet, unlinkedWalletKeyboard } from "../lib/ui.js";

/**
 * Consumes a one-time code generated by POST /api/link/generate on the
 * web dashboard. Usage: /link <CODE>
 *
 * On success, stores the Telegram chat ID against the wallet address in
 * the database - from that point on, all proposals for agents belonging
 * to that wallet are delivered to this chat. This is the production wallet<->Telegram linking flow.
 */
export async function linkCommand(ctx: Context): Promise<void> {
  const text = ctx.message && "text" in ctx.message ? ctx.message.text : "";
  const [, code] = text.trim().split(/\s+/);
  const chatId = String(ctx.chat?.id ?? "");

  if (!code) {
    await ctx.reply(
      [
        "<code>[ NEMESIS / LINK ]</code>",
        "<b>code required</b>",
        "<code>------------------------------</code>",
        "Generate a fresh code from the dashboard, then send:",
        "<code>/link YOUR-CODE</code>",
      ].join("\n"),
      { parse_mode: "HTML", ...unlinkedWalletKeyboard() },
    );
    return;
  }

  const result = await consumeLinkCode(code.toUpperCase(), chatId);

  if (!result.ok) {
    const messages: Record<string, string> = {
      "not-found": "[ NEMESIS / LINK ]\nCode not found. Copy the fresh dashboard code exactly.",
      "expired": "[ NEMESIS / LINK ]\nCode expired. Generate a new dashboard code and retry.",
      "already-used": "[ NEMESIS / LINK ]\nCode already used. Generate a new dashboard code.",
    };
    await ctx.reply(messages[result.reason] ?? "Something went wrong. Please try again.", { parse_mode: "HTML", ...unlinkedWalletKeyboard() });
    return;
  }

  const short = shortWallet(result.walletAddress);
  await ctx.reply(
    [
      "<code>[ NEMESIS / LINKED ]</code>",
      "<b>telegram relay armed</b>",
      "<code>------------------------------</code>",
      `wallet     <code>${short}</code>`,
      "delivery   proposals will arrive here",
      "approval   dashboard + wallet signature only",
      "",
      "Use <code>/agents</code> or <code>/status</code> to inspect your setup.",
    ].join("\n"),
    { parse_mode: "HTML", ...linkedWalletKeyboard() },
  );
}

/**
 * /unlink - removes the wallet<->chat mapping so proposals stop arriving.
 */
export async function unlinkCommand(ctx: Context): Promise<void> {
  const chatId = String(ctx.chat?.id ?? "");
  const { getWalletForTelegramChatId, pool } = await import("@nemesis/db");
  const wallet = await getWalletForTelegramChatId(chatId);

  if (!wallet) {
    await ctx.reply("<code>[ NEMESIS / UNLINK ]</code>\nThis chat is not linked to any wallet.", { parse_mode: "HTML", ...unlinkedWalletKeyboard() });
    return;
  }

  await pool.query("UPDATE users SET telegram_chat_id = NULL WHERE wallet_address = $1", [wallet]);

  const short = shortWallet(wallet);
  await ctx.reply([`<code>[ NEMESIS / UNLINKED ]</code>`, `<b>relay removed</b>`, `<code>------------------------------</code>`, `wallet     <code>${short}</code>`, `delivery   stopped for this chat`].join("\n"), {
    parse_mode: "HTML",
    ...unlinkedWalletKeyboard(),
  });
}