import { FragmentDivider } from "@/components/FragmentDivider";

export default function PrivacyPage() {
  return (
    <div className="mx-auto max-w-4xl px-6 py-16">
      <h1 className="font-mono text-2xl font-bold uppercase tracking-widest2 text-nm-fg">privacy policy</h1>
      <div className="mt-8">
        <FragmentDivider />
      </div>
      <div className="prose prose-invert mt-12 text-sm leading-relaxed text-nm-muted">
        <p><strong>Last updated: June 28, 2026</strong></p>
        <p>
          NEMESIS is designed to collect the minimum operational data needed to run approval-first wallet agents. This
          policy explains what data is collected, why it is used, where it may be sent, and what you can control.
        </p>

        <h2 className="text-nm-fg">1. Data we collect</h2>
        <p>
          We collect your public EVM or Solana wallet address, wallet session data, agent configurations, proposal records,
          transaction hashes that you submit for confirmation, and Telegram Chat ID when you link Telegram. We may also
          store operational runtime state for agents, such as last checked prices, last proposal time, seen token or
          pair identifiers, and proposal lifecycle status.
        </p>

        <h2 className="text-nm-fg">2. Data we do not collect</h2>
        <p>
          NEMESIS does not collect or ask for your seed phrase, private keys, wallet recovery phrase, exchange login,
          payment card data, government ID, or custodial credentials. Do not enter secrets into the app, Telegram bot,
          or Master Agent chat.
        </p>

        <h2 className="text-nm-fg">3. How data is used</h2>
        <p>
          We use wallet addresses to authenticate sessions, enforce ownership checks, store agent configuration, route
          proposals, and verify transaction confirmations. Telegram Chat IDs are used only to send proposals and bot
          responses to the linked chat. Runtime state is used to avoid duplicate proposals and keep agent checks
          consistent.
        </p>

        <h2 className="text-nm-fg">4. Master Agent and LLM processing</h2>
        <p>
          When you use the Master Agent chat interface, your natural-language prompt, recent conversation messages,
          and current wallet balance context may be sent to OpenRouter and the configured model provider to generate a
          structured strategy plan. NEMESIS does not include your wallet address in the LLM prompt. Do not include
          private keys, seed phrases, sensitive personal data, or confidential information in prompts.
        </p>

        <h2 className="text-nm-fg">5. Third-party integrations</h2>
        <p>
          NEMESIS uses third-party services to operate, including WalletConnect, Telegram, OpenRouter/model providers,
          Supabase/Postgres, Railway, Base and Solana RPC infrastructure, price feeds, DexScreener, Jupiter, and wallet software selected
          by the user. Data sent to or generated by these services may be handled under their own terms and privacy
          policies.
        </p>

        <h2 className="text-nm-fg">6. Retention</h2>
        <p>
          Agent records remain while the agent exists. Old skipped proposals are pruned automatically after 7 days.
          Approved proposal records and transaction hashes may be retained for auditability and user-facing history.
          Telegram links can be removed at any time with <code>/unlink</code>, which clears the stored Telegram Chat ID
          for the linked wallet.
        </p>

        <h2 className="text-nm-fg">7. Security controls</h2>
        <p>
          NEMESIS uses SIWE authentication, signed wallet sessions, ownership checks on sensitive routes, cross-origin
          rejection on mutating web routes, one-time Telegram link codes, and transaction confirmation checks that
          compare signer, chain, destination, value, calldata, or Solana transaction message data against the stored proposal payload.
        </p>

        <h2 className="text-nm-fg">8. Your choices</h2>
        <p>
          You can disconnect your wallet in your wallet UI, unlink Telegram with <code>/unlink</code>, pause or resume
          agents from the dashboard or bot, and decline any proposal by not signing it. You can request deletion of
          operational records by contacting the project owner through the official NEMESIS support channel.
        </p>
      </div>
    </div>
  );
}
